[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

# exact route for monthly metrics
[[redirects]]
  from = "/api/metrics/monthly"
  to   = "/.netlify/functions/metrics-monthly"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  # Scheduled function to update product costs hourly
[functions."scheduled-update-product-costs"]
  schedule = "0 * * * *"

  # Scheduled function to update shipping costs hourly
[functions."scheduled-update-shipping-costs"]
  schedule = "0 * * * *"

  [[functions]]
  path = "netlify/functions/scheduled-update-employee-salaries.mjs"
  schedule = "0 * * * *"  # Runs every hour at the top of the hour
